repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        exclude: "^.*/tsconfig.*.json$"
      - id: check-toml
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-added-large-files
        args: [--maxkb=15000]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending

  # Removes unnecessary # noqa comments.
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  # Check for blanket (overly broad) noqa comments and encourage type annotations.
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==24.4.2]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
        args: [--profile=black]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write]
        types_or: [css, json, yaml, markdown]
        additional_dependencies:
          - prettier@3.2.5

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
          ]

  - repo: local
    hooks:
      - id: mkdocs-build
        name: Build MkDocs
        entry: mkdocs build --strict
        language: system
        pass_filenames: false
        files: '^(mkdocs\.yml|docs/.*\.md)$'
