site_name: DSA4264 Team Detoxify Technical Report
# Configuration
# Catalogue of themes: https://github.com/mkdocs/catalog?tab=readme-ov-file#-theming
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - content.tabs.link
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to automatic mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
# Plugins
plugins:
  - blog:
      blog_toc: true
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-jupyter
  - render_swagger
hooks:
  - pyscripts/authors/authors.py
  - pyscripts/doculabels/doculabels.py

extra:
  authors:
    - Joy Tan:
        alias: joy
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/156385027?v=4
        url: https://github.com/joytsy
    - Kylie Tan:
        alias: kylie
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/157715357?v=4
        url: https://github.com/kyliextan
    - Koh Yi Jing:
        alias: yijing
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/134367210?v=4
        url: https://github.com/yijingkoh
    - Richmond Sin:
        alias: richmond
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/110978236?v=4
        url: https://github.com/richmondsin
    - Sarah Goh:
        alias: sarah
        role: Contributor
        avatar: https://avatars.githubusercontent.com/u/130122483?v=4
        url: https://github.com/sarahlahlah

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - styles/mermaid.css
  - styles/author.css
  - styles/doculabels.css

nav:
  - Home:
      - index.md
      - Technical Report:
          - home/technical_report/context.md
          - home/technical_report/scope.md
          - Methodology:
              - home/technical_report/methodology/index.md
              - Data Processing:
                  - home/technical_report/methodology/data-processing/index.md
              - Modelling:
                  - Text Classification Model: home/technical_report/methodology/modelling/model1.md
                  - Topic Modelling: home/technical_report/methodology/modelling/model2.md
              - Application:
                  - home/technical_report/methodology/application/index.md
          - home/technical_report/findings.md
